version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: realworld-postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=realworld-db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ..              # On remonte à la racine du projet pour voir "app/"
      dockerfile: docker/Dockerfile
    container_name: realworld-api
    ports:
      - '3000:3000'            # Accès via http://localhost:3000
    environment:
      # IMPORTANT : On remplace 'localhost' par 'db' (le nom du service ci-dessus)
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/realworld-db?schema=public
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - db                     # L'API attend que la DB soit lancée

volumes:
  db_data: